import { type NextPage } from "next";
import Head from "next/head";

import NavButton from "../components/button/NavButton";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Monroe&apos;s Profile</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavButton />
            <p>Home page</p>
        </>
    );
};

export default Home;
